# Form implementation generated from reading ui file 'picard-plugin-performer-tag-replace/options_performer_tag_replace.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_PerformerTagReplaceOptionsPage(object):
    def setupUi(self, PerformerTagReplaceOptionsPage):
        PerformerTagReplaceOptionsPage.setObjectName("PerformerTagReplaceOptionsPage")
        PerformerTagReplaceOptionsPage.resize(505, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PerformerTagReplaceOptionsPage.sizePolicy().hasHeightForWidth())
        PerformerTagReplaceOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(PerformerTagReplaceOptionsPage)
        self.vboxlayout.setSpacing(16)
        self.vboxlayout.setObjectName("vboxlayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.page_title = QtWidgets.QLabel(parent=PerformerTagReplaceOptionsPage)
        font = QtGui.QFont()
        # font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout_4.addWidget(self.page_title)
        self.format_description = QtWidgets.QLabel(parent=PerformerTagReplaceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        # font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        self.format_description.setFont(font)
        self.format_description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.format_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.verticalLayout_4.addWidget(self.format_description)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.performer_tag_replace_performers = QtWidgets.QCheckBox(parent=PerformerTagReplaceOptionsPage)
        self.performer_tag_replace_performers.setChecked(False)
        self.performer_tag_replace_performers.setObjectName("performer_tag_replace_performers")
        self.verticalLayout_4.addWidget(self.performer_tag_replace_performers)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.replacement_section_title = QtWidgets.QLabel(parent=PerformerTagReplaceOptionsPage)
        font = QtGui.QFont()
        # font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        self.replacement_section_title.setFont(font)
        self.replacement_section_title.setObjectName("replacement_section_title")
        self.verticalLayout_4.addWidget(self.replacement_section_title)
        self.performer_tag_replacement_pairs = QtWidgets.QPlainTextEdit(parent=PerformerTagReplaceOptionsPage)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.performer_tag_replacement_pairs.setFont(font)
        self.performer_tag_replacement_pairs.setObjectName("performer_tag_replacement_pairs")
        self.verticalLayout_4.addWidget(self.performer_tag_replacement_pairs)
        self.vboxlayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(PerformerTagReplaceOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(PerformerTagReplaceOptionsPage)

    def retranslateUi(self, PerformerTagReplaceOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        PerformerTagReplaceOptionsPage.setWindowTitle(_translate("PerformerTagReplaceOptionsPage", "window.title"))
        self.page_title.setText(_translate("PerformerTagReplaceOptionsPage", "page.title"))
        self.format_description.setText(_translate("PerformerTagReplaceOptionsPage", "page.text"))
        self.performer_tag_replace_performers.setText(_translate("PerformerTagReplaceOptionsPage", "page.cb.replace_performers"))
        self.replacement_section_title.setText(_translate("PerformerTagReplaceOptionsPage", "section.replacement.title"))
        self.performer_tag_replacement_pairs.setPlaceholderText(_translate("PerformerTagReplaceOptionsPage", "section.replacement.placeholder"))
